pull_request_rules:
  - name: automatic merge for pre-commit ci updates
    conditions:
      - author=pre-commit-ci[bot]
      - check-success=pre-commit.ci - pr
    actions:
      merge:
        method: squash
