line-length = 100
target-version = "py312"


[lint]
future-annotations = true
preview = true
select = [
  "F",
  "E",
  "W",
  "C90",
  "I",
  "N",
  "UP",
  "ANN",
  "ASYNC",
  "S",
  "B",
  "A",
  "C4",
  "DTZ",
  "EM",
  "FA",
  "ISC",
  "LOG",
  "G",
  "PIE",
  "T20",
  "PT",
  "RSE",
  "RET",
  "SLOT",
  "SIM",
  "TC",
  "ARG",
  "PTH",
  "PL",
  "TRY",
  "FAST",
  "PERF",
  "FURB",
  "RUF",
]
ignore = [
  "assert",    # Assert used
  "magic-value-comparison", # Magic value used
  "ambiguous-unicode-character-comment",  # Comment contains ambiguous character
  "no-self-use", # Method could be a function, class method, or static method
  "any-type",  # typing.Any used
  "call-datetime-strptime-without-zone",  # Naive datetime constructed

  # Custom ignores for this project
  "asyncio-dangling-task",  # Store a reference to the return value of asyncio.create_task
  "line-too-long",    # Line too long
  "too-many-arguments", # Too many arguments in function definition
  "too-many-positional-arguments", # Too many positional arguments
  "too-many-public-methods", # Too many public methods
  "raise-within-try",  # Abstract raise to an inner function
  "implicit-return",  # Missing explicit return statements
  "suspicious-non-cryptographic-random-usage",    # Cryptographically weak pseudo-random number generator used
  "non-pep695-generic-class",   # TypeVar used
  "non-pep695-type-alias",   # TypeAlias used
  "hardcoded-password-string",    # Possible hardcoded password assigned to variable
  "suspicious-pickle-usage",    # pickle module used
  "suspicious-pickle-import",    # pickle module used
  "ambiguous-variable-name",    # Ambiguous variable name
  "missing-type-args",  # Missing type annotation for *args
  "missing-type-kwargs",  # Missing type annotation for **kwargs

  # Refactor related ignores
  "complex-structure",    # Function is too complex
  "too-many-locals", # Too many local variables
  "too-many-statements", # Too many statements
  "too-many-branches", # Too many branches
  "too-many-return-statements", # Too many return statements
  "too-many-statements-in-try-clause", # Try clause contains too many statements
]

[lint.per-file-ignores]
"**/__init__.py" = ["undefined-local-with-import-star", "unused-import"]
"./migrations/*.py" = ["ALL"]
"hoyo_buddy/draw/**/*.py" = ["PLR", "C"]
"hoyo_buddy/draw/drawer.py" = ["undefined-local-with-import-star-usage"]
"hoyo_buddy/models.py" = ["typing-only-third-party-import"]
"test_*.py" = ["ALL"]
"test.py" = ["ALL"]
"restart.py" = ["print", "subprocess-popen-with-shell-equals-true", "suspicious-subprocess-import", "subprocess-without-shell-equals-true", "start-process-with-partial-path", "try-consider-else"]
"rolling_restart.py" = ["print", "subprocess-popen-with-shell-equals-true", "suspicious-subprocess-import", "subprocess-without-shell-equals-true", "start-process-with-partial-path", "try-consider-else"]
"tools/*.py" = ["print"]
"scripts/*.py" = ["ALL"]

[lint.flake8-type-checking]
runtime-evaluated-base-classes = [
  "pydantic.BaseModel",
  "pydantic_settings.BaseSettings",
]
runtime-evaluated-decorators = [
  "discord.ext.commands.command",
  "discord.app_commands.command",
  "fastapi.APIRouter.get",
  "fastapi.APIRouter.post",
  "fastapi.APIRouter.put",
  "fastapi.APIRouter.delete",
]

[lint.mccabe]
max-complexity = 15

[lint.pydocstyle]
convention = "google"

[lint.isort]

split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
