{
 "title": "Hoyo Buddy",
 "description": "Hoyo Buddy Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(discordbot_connected, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Command Count in 24 Hr",
   "type": "bargauge",
   "description": "過去 24 小時各指令使用數量",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(command) (increase(discordbot_on_slash_command_total{job=\"$job\", command!=\"None\"}[24h]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "discordbot_user_installs_total", "legendFormat": "__auto" },
    {
     "expr": "discordbot_guilds_total{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "discordbot_accounts_total{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - discordbot_process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "discordbot_connected{job=~\"$job\", shard=\"None\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "discordbot_connected{job=~\"$job\",shard=~'[0-9]+'}",
     "legendFormat": "{{job}} : {{shard}}"
    }
   ]
  },
  {
   "title": "Guilds Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "discordbot_guilds_total{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Discord Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "discordbot_latency_seconds{job=~\"$job\", shard=~\"[0-9]+\"}",
     "legendFormat": "{{job}} : {{shard}}"
    },
    {
     "expr": "discordbot_latency_seconds{job=~\"$job\", shard=\"None\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Accounts Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "discordbot_accounts_total{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "discordbot_cpu_usage_percent{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "User Installs Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "discordbot_user_installs_total{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Process)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "targets": [
    {
     "expr": "discordbot_memory_usage{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Command Activity",
   "type": "timeseries",
   "description": "每 10 分鐘各指令使用數折線圖",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(job, command) (changes(discordbot_on_slash_command_total{job=~\"$job\", command!=\"None\"}[$__interval])) > 0",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}