name: Biweekly Release

on:
  schedule:
    - cron: "0 0 1,15 * *"
  workflow_dispatch:

jobs:
  biweekly-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Update version number
        uses: seriaati/update-ver-num@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: seriaati/create-release@main
