name: Create release

on:
  push:
    branches:
      - main
    paths:
      - pyproject.toml
      - uv.lock
      - .github/workflows/release.yml

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Create release
        uses: seriaati/create-release@main
